bonsai-rx/docs

README.md
I noticed that the ~ doesn't work in this repo for creating an absolute link to the root directory. Based on other project's suggestions online, I have changed these absolute links to relative links, which works locally.
=> Change syntax for relative links

docfx.json, templates/html/styles/main.css, worksheets/acquisition.md, worksheets/closed-loop.md, worksheets/scripting.md, worksheets/state-machines.md, worksheets/synching-ephys.md, worksheets/synching.md, worksheets/vision-psychophysics.md
This PR converts the existing worksheets to markdig compatible syntax. To make everything work we enabled a few CSS elements for `summary` HTML tags and a new CSS class for centered diagrams (`.diagram`).
Fixes #36
=> Convert equivalent worksheet kramdown syntax to markdig

template/styles/main.js
This PR handles an edge case where code blocks missing a language identifier would break the jQuery layout script inserting the DOM table header for the copy button. It also fixes casing for language identifiers commonly used in the docs.
Fixes #64
=> Allow code blocks with empty language identifier

articles/cli.md
This PR simplifies code block syntax for inline blocks (only one backtick is needed rather than three).
=> Simplify inline code block syntax

apidoc/Bonsai_Expressions_ParseBuilder.md, apidoc/Bonsai_Expressions_ParseBuilder_Pattern.md, apidoc/Bonsai_Expressions_ParseBuilder_Separator.md, articles/expressions-parse.md
This PR adds extended documentation for the `Parse` operator. It describes in detail the workings of the `Pattern` and `Separator` properties and how they can be used by themselves, or in combination. It also describes each of the placeholder strings, and includes a small table with examples for matching different types of formatted strings.
=> Add extended docs for the parse operator

articles/expressions-parse.md
This is a simple fix to ensure heading levels do not obscure the hierarchy in the table of contents. For future reference, in extended docs the default heading for sub-sections in DocFX class documentation is `h3` or `###`.
=> Ensure consistent heading level

apidoc/Bonsai_Expressions_BooleanProperty.md, apidoc/Bonsai_Expressions_ByteProperty.md, apidoc/Bonsai_Expressions_DateTimeOffsetProperty.md, apidoc/Bonsai_Expressions_DateTimeProperty.md, apidoc/Bonsai_Expressions_DoubleProperty.md, apidoc/Bonsai_Expressions_FloatProperty.md, apidoc/Bonsai_Expressions_Int64Property.md, apidoc/Bonsai_Expressions_IntProperty.md, apidoc/Bonsai_Expressions_PropertySource.md, apidoc/Bonsai_Expressions_PropertySource_2.md, apidoc/Bonsai_Expressions_StringProperty.md, apidoc/Bonsai_Expressions_TimeSpanProperty.md, apidoc/Bonsai_Expressions_WorkflowProperty.md, apidoc/Bonsai_Expressions_WorkflowProperty_1.md, articles/expressions-propertysource.md
This PR adds extended documentation for property sources. Both built-in workflow properties (e.g. `BooleanProperty`, `ByteProperty`, etc.) and editor-created property sources share the same basic logic.
=> Add extended documentation for property sources

apidoc/Bonsai_Expressions_AddBuilder.md, apidoc/Bonsai_Expressions_BitwiseAndBuilder.md, apidoc/Bonsai_Expressions_BitwiseOrBuilder.md, apidoc/Bonsai_Expressions_DivideBuilder.md, apidoc/Bonsai_Expressions_EqualBuilder.md, apidoc/Bonsai_Expressions_GetValueOrDefaultBuilder.md, apidoc/Bonsai_Expressions_GreaterThanBuilder.md, apidoc/Bonsai_Expressions_GreaterThanOrEqualBuilder.md, apidoc/Bonsai_Expressions_IndexBuilder.md, apidoc/Bonsai_Expressions_LeftShiftBuilder.md, apidoc/Bonsai_Expressions_LessThanBuilder.md, apidoc/Bonsai_Expressions_LessThanOrEqualBuilder.md, apidoc/Bonsai_Expressions_LogicalAndBuilder.md, apidoc/Bonsai_Expressions_LogicalOrBuilder.md, apidoc/Bonsai_Expressions_ModBuilder.md, apidoc/Bonsai_Expressions_MultiplyBuilder.md, apidoc/Bonsai_Expressions_NotEqualBuilder.md, apidoc/Bonsai_Expressions_RightShiftBuilder.md, apidoc/Bonsai_Expressions_SubtractBuilder.md, apidoc/Bonsai_Expressions_XorBuilder.md, articles/expressions-binaryoperator-argument.md, articles/expressions-binaryoperator.md
This PR adds documentation on some of the nuances of using the built-in binary operators, including rules for operating on sequences of pairs, or sequences of single values with automatically inferred properties.
=> Add extended documentation for binary operators

apidoc/Bonsai_Expressions_ExternalizedMappingBuilder.md, apidoc/Bonsai_Expressions_InputMappingBuilder.md, apidoc/Bonsai_Expressions_PropertyMappingBuilder.md, articles/expressions-externalizedmapping.md, articles/expressions-inputmapping.md, articles/expressions-propertymapping-multiple.md, articles/expressions-propertymapping.md, articles/property-mapping.md
This PR refactors existing documentation to be reused for both conceptual and technical reference manuals. It can be common for readers to engage with the docs from multiple entry points so it will be useful to make that work while maintaining a single source to avoid duplicating content.
=> Add extended documentation for property mapping operators

apidoc/Bonsai_Expressions_GroupWorkflowBuilder.md, apidoc/Bonsai_Expressions_IncludeWorkflowBuilder.md, apidoc/Bonsai_Expressions_WorkflowInputBuilder.md, apidoc/Bonsai_Expressions_WorkflowInputBuilder_1.md, apidoc/Bonsai_Expressions_WorkflowOutputBuilder.md, articles/expressions-groupworkflow.md, articles/expressions-includeworkflow.md, articles/expressions-sharedstate.md, articles/expressions-workflowinput.md, articles/expressions-workflowoutput.md
This PR adds extended documentation covering details of the core nesting group nodes: `GroupWorkflow` and `IncludeWorkflow`. It also discusses the details of routing inputs and outputs to the nested workflow using the `WorkflowInput` and `WorkflowOutput` operators.
=> Add extended documentation for nesting group nodes

apidoc/Bonsai_Expressions_DisableBuilder.md, apidoc/Bonsai_Expressions_MemberSelectorBuilder.md, apidoc/Bonsai_Expressions_UnitBuilder.md, apidoc/Bonsai_Expressions_UnknownTypeBuilder.md, articles/expressions-disable.md, articles/expressions-memberselector.md, articles/expressions-unit.md, articles/expressions-unknowntype.md
This PR adds missing extended documentation for the `Unit`, `MemberSelector`, `UnknownTypeBuilder` and `DisableBuilder` operators. These operators round up the main core functionality of the expressions namespace.
=> Add extended documentation for missing core operators

apidoc/Bonsai_Expressions_VisualizerMappingBuilder.md, articles/expressions-visualizermapping.md
This PR adds a slightly more extended discussion of the new `VisualizerMapping` operator. A more in-depth discussion of visualizers and visualizer composition remains due, but this will work as a starting point for now.
=> Add extended documentation for visualizer mapping operator

.github/workflows/build.yml, .github/workflows/gha.py, .github/workflows/update-bonsai-version-info.py, .github/workflows/version-bump.yml, .github/workflows/version-info-template.md, README.md, articles/installation.md
This PR supports changes needed by https://github.com/bonsai-rx/bonsai/pull/1873
It also cleans up the existing build workflow substantially and migrates it to modern GitHub Pages deployment.
This PR is complete, but is marked as a draft because it cannot be merged until some manual repository configuration is done first.
=> Add infrastructure for release automation and clean up build workflow

.github/workflows/build.yml
With this approach the error still appears in the workflow run overview letting the user know what they need to change.
This approach also avoids requiring forks to add an Actions variable *and* changing the GitHub Pages deployment setting. (They'll only need to do the latter.)
Fixes https://github.com/bonsai-rx/docs/issues/88
=> Make GitHub Pages deployment optional on non-canonical forks

.config/dotnet-tools.json, docfx.json
The new DocFX release resolves the regression with external `xrefmap.yml` files so we are again safe to upgrade. Following the recommendation in #90 we have also turned on exporting of the `sitemap.xml` file for more efficient crawling.
=> Update docfx version and export sitemap

.github/workflows/version-bump.yml
This allows CI to bypass the pull request requirement for pushing to `main`
As an unintended consequence of this change, the manual GitHub Pages deployment is no longer necessary as GitHub's recursion protection doesn't block pushes from deployment keys.
A nice side-effect of this is that the build of the docs repo upon release is now attributed to a human rather than the GitHub Actions bot, which means that build failure notifications actually go to someone now 😁
=> Use deployment key in CI for manipulating Git repository

articles/environments.md
Closes #99 
I have updated the article to add the template method and also chose to keep the original portable method as another option. In doing so I also reorganised the article to:
- pull out the background information into an "Environment Basics" sections
- added a tip alert at the front of each section to inform users about when they might choose/need to use that section.
- removed redundant/outdated information.
=> Update Environments article with template method

docfx.json
Recent CI builds started failing due to issues resolving project reference dependencies internal to the bootstrapper projects. The reason is unknown although the logs reveal several issues relating to NuGet audit failures.
Further investigation might reveal a reason, however, bootstrapper projects do not currently contain any public APIs and so do not contain XML documentation comments. Their CLI interface is currently documented manually and therefore they do not need to be included in docfx metadata.
This PR fixes the CI build issue and improves docs build times by simply removing all bootstrapper projects and their indirect dependencies from the docfx metadata.
=> Remove bootstrapper projects from docfx metadata

.config/dotnet-tools.json, articles/cli.md, articles/create-package.md, articles/design-guidelines.md, articles/editor.md, articles/environments.md, articles/gallery.md, articles/higher-order.md, articles/installation.md, articles/observables.md, articles/operators.md, articles/packages.md, articles/property-mapping.md, articles/scripting-extensions.md, articles/subjects.md, articles/toc.yml, articles/workflow-guidelines.md
To improve visibility of all documentation topics, this PR flattens the conceptual documentation table of contents. The number of sections is not so large right now to require collapsing hierarchies, and we can always change in the future as needed.
The version of docfx is also updated and we removed duplication of article titles throughout both metadata and TOC declarations. Minor wording tweaks were made to improve style consistency and readability.
=> Flatten table of contents for conceptual documentation

docfx.json
The default sort order for enum values in DocFX is alphabetical order for some reason. This is unintuitive in several cases as it decouples enum values from their natural clustering in code.
This PR restores enum presentation layout to declaration order.
=> Ensure enum values are shown in declaring order

docfx.json
Currently the readability of operator docs is made more difficult by the various snippets of C# code which are scattered through the default inline version of the DocFX managed reference layout.
By using the separate member pages layout we remove all snippets and technical details, which are now replaced by a smaller table of contents providing at a glance all properties and process methods. This will be the first step towards defining a more standardized template for operator classes.
=> Use separate member pages for technical reference docs

articles/documentation-style-guide.md
Based on what we uncovered in the most recent [DCM](https://github.com/orgs/bonsai-rx/discussions/2122) for this [issue](https://github.com/bonsai-rx/docs/issues/122) to simplify operator referencing, reduce repetition, as well as improve consistency across documentation.
Not sure if we also discovered this in the meeting, but the reference link could be made even simpler (double brackets are not necessary, and the name change for the operator could be done by changing the reference name).
=> Update operator formatting guidelines with reference style link method

articles/installation.md
This PR adds a link to the GitHub release page for the Bonsai core repository, with pre-releases filtered out.
This should help people decide whether to upgrade to the latest Bonsai version, especially those who don’t actively live on GitHub😄.
We previously discussed adding release notes as a menu option in the editor, which is still an option. However, linking to the release page seems like a more natural way for people to check release notes.
=> Add link to release notes on installation page

template/public/main.css
The modern theme default styling for keyboard shortcuts is a little bit too high-contrast so we tweak it slightly to make it more subtle. This PR updates the submodule to the latest version, which apparently had not been done in a while, but hopefully everything should have kept consistent.
=> Update default styling of keyboard shortcuts

apidoc/Bonsai_Vision_Crop.md, apidoc/Bonsai_Vision_CropCanvas.md, apidoc/Bonsai_Vision_CropPolygon.md, apidoc/Bonsai_Vision_GoodFeaturesToTrack.md, apidoc/Bonsai_Vision_MaskPolygon.md, apidoc/Bonsai_Vision_RoiActivity.md, articles/roi-editor.md, articles/roi-polygon-editor.md
Fixes #134.
After reviewing the operators, it looks like there are only five operators in the current `Bonsai.Core` docs that use a ROI editor, and there are two main variants, a single ROI editor and one that accepts polygonal/multiple editors. Thus I have created two `overwrite` markdown snippets that can be included with each operator.
There may be other `ROI editors` used by operators outside of `Bonsai.Core`. For example `ScreenCaptureStream` uses an `IplImageOutputRectangleEditor` but the `Bonsai.Video` package doesn’t have a website setup yet. I will just make a note and address them as I come across them.
=> Add ROI editor instructions for operators with ROI properties
